[loggers]
keys=root,userLogger,shoppingLogger

[handlers]
keys=consoleHandler, userHandler, shoppingHandler

[formatters]
keys=sampleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_userLogger]
level=INFO
handlers=userHandler
qualname=userLogger
propagate=0

[logger_shoppingLogger]
level=INFO
handlers=shoppingHandler
qualname=shoppingLogger
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=sampleFormatter
args=(sys.stdout,)

[handler_userHandler]
class=FileHandler
level=INFO
formatter=sampleFormatter
args=('userLog.log',)

[handler_shoppingHandler]
class=FileHandler
level=INFO
formatter=sampleFormatter
args=('shoppingList.log',)

[formatter_sampleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s